### PR TITLE
YONK-16: Added split module store for tests

### PR DESCRIPTION
**Pull request by aamishbaloch**

### CODE REVIEW

**Comment by aamishbaloch** [comment]
@ziafazal Can you review this?

**Review by ziafazal — CHANGES_REQUESTED** [review]
@aamishbaloch I'd suggest to remove commented code and add dual module_store test support for all tests in in test_workgroups.py.

**Comment by aamishbaloch** [comment]
@ziafazal Done with the suggested changes. Can you review this?

**Review by ziafazal — APPROVED** [review]
👍

**Pull request merged**
